[graph]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
yanked = "deny"
unmaintained = "workspace"

[bans]
multiple-versions = "deny"
wildcards = "warn"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
