//! `cairn pair` â€” claim a pairing code generated by a Cairn server.
//!
//! The host mints a short-lived, single-use code (from `cairn pair-code`). A new device claims it
//! over the network to receive its device token.

use crate::State;
use anyhow::{Context, Result};
use serde_json::{json, Value};

/// New-device side: claim a code from a server, store the device token, and run an initial sync.
pub fn claim(state: &State, server: &str, code: &str) -> Result<()> {
    let server = server.trim_end_matches('/');
    let body: Value = ureq::post(&format!("{server}/api/pair/claim"))
        .send_json(json!({ "code": code.trim() }))
        .map_err(|e| anyhow::anyhow!("pairing failed (is the code valid and unexpired?): {e}"))?
        .into_json()
        .context("decoding the pairing response")?;

    let token = body
        .get("token")
        .and_then(Value::as_str)
        .context("the server returned no token")?;
    let name = body.get("name").and_then(Value::as_str).unwrap_or("device");

    // Remember the token so future `cairn sync --server <url>` works without re-entering it.
    state
        .store
        .set_meta(&format!("device_token:{server}"), token)?;

    println!("paired as '{name}'. syncingâ€¦");
    crate::sync::run(&state.store, server, Some(token))
}
