//! Feature 005 adds no datastore, no broker and no worker platform (T159,
//! SC-737, Constitution Principle II).
//!
//! **This file needs no database.** Every assertion here is a fact about
//! `Cargo.toml` text, checked against `tests/feature005/dependency-baseline.toml`
//! — the pre-005 manifest recorded before this feature touched a single line
//! of Rust. There is nothing here a running server or store could tell us
//! that the manifests themselves do not already say, so there is no `pg!()`
//! skip macro in this file: it always runs.
//!
//! # Why a recorded baseline, and not a live diff against `main`
//!
//! SC-737 is a claim about *this feature's own additions*, which is only
//! checkable against a manifest frozen before the feature existed. Comparing
//! against `main` at test time would compare against whatever `main` happens
//! to be today — itself possibly already carrying Feature 005 merged in —
//! which proves nothing. `dependency-baseline.toml` is that frozen point: a
//! committed file, not regenerated by this test under any circumstance.
//!
//! # Why substring matching, not exact-name matching
//!
//! The baseline's own comment states the reasoning and this file inherits it
//! unchanged: matching a forbidden pattern as a substring of the folded crate
//! name (case folded, `-`/`_` removed) is the conservative direction. A false
//! positive here is a five-minute conversation about whether a dependency
//! belongs; a false negative is Principle II quietly breaking with nothing to
//! catch it.
//!
//! # What this file does *not* claim
//!
//! It does not claim the workspace added *zero* dependencies — plenty of
//! ordinary ones are legitimate. It claims specifically that nothing added
//! falls in the datastore, broker or worker-platform categories the baseline
//! names — and it reads those category names and patterns from the baseline
//! file itself, rather than hard-coding them here, so a category the baseline
//! grows later is enforced without this file changing.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use toml_edit::{DocumentMut, Item, Table};

fn workspace_root() -> PathBuf {
    // `CARGO_MANIFEST_DIR` is `tests/`; the workspace root is its parent.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("tests/ has a parent")
        .to_path_buf()
}

fn read(root: &Path, rel: &str) -> String {
    let path = root.join(rel);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()))
}

fn parse(text: &str, label: &str) -> DocumentMut {
    text.parse::<DocumentMut>()
        .unwrap_or_else(|e| panic!("parsing {label} as TOML: {e}"))
}

/// Navigate a dotted path (`"workspace.dependencies"`) from a document's root
/// table into whatever table-like item sits at the end of it, or `None` if
/// any segment along the way is absent — which is the ordinary case for a
/// manifest that has no `[dev-dependencies]` section at all, not an error.
fn table_at<'a>(doc: &'a DocumentMut, dotted: &str) -> Option<&'a dyn toml_edit::TableLike> {
    let mut parts = dotted.split('.');
    let first = parts.next()?;
    let mut item: &Item = doc.as_table().get(first)?;
    for part in parts {
        item = item.as_table_like()?.get(part)?;
    }
    item.as_table_like()
}

/// The dependency-table keys (crate names) present under `dotted` in `doc`,
/// or an empty vec if that table does not exist in this manifest — a manifest
/// with no `[dev-dependencies]` table has no dev-dependencies, not a parse
/// failure.
fn dependency_names(doc: &DocumentMut, dotted: &str) -> Vec<String> {
    match table_at(doc, dotted) {
        Some(t) => t.iter().map(|(k, _)| k.to_string()).collect(),
        None => Vec::new(),
    }
}

fn string_array(table: &Table, key: &str) -> Vec<String> {
    table
        .get(key)
        .and_then(Item::as_array)
        .unwrap_or_else(|| panic!("`{key}` is not an array in the baseline"))
        .iter()
        .map(|v| {
            v.as_str()
                .unwrap_or_else(|| panic!("`{key}` has a non-string entry in the baseline"))
                .to_string()
        })
        .collect()
}

/// Fold a crate name the way the baseline's own patterns are matched:
/// lower-cased, with `-` and `_` removed, so `tokio-postgres`, `tokio_postgres`
/// and `TokioPostgres` are one and the same string for matching purposes.
fn fold(name: &str) -> String {
    name.to_lowercase().replace(['-', '_'], "")
}

struct Baseline {
    manifests: Vec<String>,
    tables: Vec<String>,
    entries: BTreeSet<String>,
    /// (category name, reason, folded patterns) — read generically from every
    /// `[forbidden.*]` table the baseline happens to declare, so a category
    /// added to the baseline later is enforced without touching this file.
    forbidden: Vec<(String, String, Vec<String>)>,
    extraction_declared: Vec<String>,
}

fn load_baseline(root: &Path) -> Baseline {
    let text = read(root, "tests/feature005/dependency-baseline.toml");
    let doc = parse(&text, "tests/feature005/dependency-baseline.toml");

    let manifest = doc["manifest"]
        .as_table()
        .expect("baseline has a [manifest] table");
    let manifests = string_array(manifest, "manifests");
    let tables = string_array(manifest, "tables");
    let entries: BTreeSet<String> = string_array(manifest, "entries").into_iter().collect();

    let mut forbidden = Vec::new();
    if let Some(forbidden_table) = doc.as_table().get("forbidden").and_then(Item::as_table) {
        for (category, item) in forbidden_table.iter() {
            let sub = item
                .as_table()
                .unwrap_or_else(|| panic!("[forbidden.{category}] is not a table"));
            let reason = sub
                .get("reason")
                .and_then(Item::as_str)
                .unwrap_or("(no reason recorded)")
                .to_string();
            let patterns: Vec<String> = string_array(sub, "patterns")
                .into_iter()
                .map(|p| fold(&p))
                .collect();
            forbidden.push((category.to_string(), reason, patterns));
        }
    }
    assert!(
        !forbidden.is_empty(),
        "the baseline declares no [forbidden.*] category at all — either the file was \
         truncated or this test is reading the wrong section, and either way SC-737 would be \
         enforcing nothing"
    );

    let extraction_declared = doc
        .as_table()
        .get("extraction")
        .and_then(Item::as_table)
        .map(|t| string_array(t, "declared"))
        .unwrap_or_default();

    Baseline {
        manifests,
        tables,
        entries,
        forbidden,
        extraction_declared,
    }
}

/// Every dependency name the current workspace declares, read from exactly
/// the manifests and dependency tables the baseline itself names — so this
/// test asks the same question of today's tree that was asked when the
/// baseline was recorded, not a different one.
fn current_entries(root: &Path, baseline: &Baseline) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    for manifest_rel in &baseline.manifests {
        let text = read(root, manifest_rel);
        let doc = parse(&text, manifest_rel);
        for table in &baseline.tables {
            for name in dependency_names(&doc, table) {
                out.insert(name);
            }
        }
    }
    out
}

/// The gate: nothing added since the baseline may fall in a forbidden
/// category (SC-737, Principle II). Additions outside those categories are
/// unconstrained here — this file has no opinion on whether the workspace may
/// grow an ordinary dependency, only on whether it grew a datastore, a broker
/// or a worker platform.
#[test]
fn no_dependency_added_since_the_baseline_is_a_datastore_broker_or_worker_platform() {
    let root = workspace_root();
    let baseline = load_baseline(&root);
    let current = current_entries(&root, &baseline);

    let added: Vec<&String> = current.difference(&baseline.entries).collect();

    let mut violations: Vec<String> = Vec::new();
    for name in &added {
        // A dependency the feature explicitly declared for a hosted
        // extraction provider is carved out of SC-737 by name
        // (FR-805a/FR-805a1) and is not tested against the forbidden
        // categories here — `contracts/extraction.md` §5 is its gate, not
        // this file.
        if baseline.extraction_declared.iter().any(|d| d == *name) {
            continue;
        }
        let folded = fold(name);
        for (category, reason, patterns) in &baseline.forbidden {
            if let Some(pattern) = patterns.iter().find(|p| folded.contains(p.as_str())) {
                violations.push(format!(
                    "`{name}` was added since the baseline and matches the {category} pattern \
                     `{pattern}` ({reason})"
                ));
            }
        }
    }

    assert!(
        violations.is_empty(),
        "SC-737 forbids a new datastore, broker or worker-platform dependency; found:\n  {}\n\
         (baseline recorded at commit {} — see tests/feature005/dependency-baseline.toml)",
        violations.join("\n  "),
        std::fs::read_to_string(root.join("tests/feature005/dependency-baseline.toml"))
            .map(|_| "see file header")
            .unwrap_or("unknown"),
    );

    eprintln!(
        "feature005_architecture: {} dependenc{} added since the baseline, none forbidden: {:?}",
        added.len(),
        if added.len() == 1 { "y" } else { "ies" },
        added.iter().map(|s| s.as_str()).collect::<Vec<_>>()
    );
}

/// A sanity check on the baseline-reading machinery itself: if this test
/// somehow read zero entries or zero manifests, the gate above would pass
/// vacuously (an empty `current` has nothing to diff), and a vacuous pass is
/// worse than no test at all.
#[test]
fn the_baseline_and_the_current_workspace_are_both_non_trivial() {
    let root = workspace_root();
    let baseline = load_baseline(&root);
    assert!(
        baseline.entries.len() > 20,
        "the recorded baseline has suspiciously few entries ({}); either the workspace at \
         the baseline commit was tiny or this test mis-parsed the file",
        baseline.entries.len()
    );
    assert!(
        baseline.manifests.len() >= 9,
        "the baseline names suspiciously few manifests ({})",
        baseline.manifests.len()
    );

    let current = current_entries(&root, &baseline);
    assert!(
        current.len() > 20,
        "the current workspace's dependency scan found suspiciously few entries ({}); a \
         parsing regression here would silently make the gate above vacuous",
        current.len()
    );

    // The baseline's own worked example (`cairn-core`, `cairn-store`, ...) —
    // in-workspace path dependencies are deliberately counted, so a new
    // workspace member shows up as an addition too.
    for expected in ["cairn-core", "cairn-store", "sqlx", "tokio"] {
        assert!(
            current.contains(expected),
            "expected `{expected}` to be part of the current workspace's dependency scan"
        );
    }
}
