use std::path::Path;

fn main() {
    // rust-embed requires the embedded folder to exist at compile time, but the Next.js UI is
    // generated by `npm run build` and is not committed. Make sure a directory exists so that a
    // plain `cargo check` from a fresh clone succeeds and the embedded fallback page is used until
    // the web UI is built.
    let out_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/out");
    if !out_dir.exists() {
        std::fs::create_dir_all(&out_dir).expect("create web/out for rust-embed");
    }
}
