use std::path::Path;

fn main() {
    // rust-embed requires the embedded folder to exist at compile time, but the Next.js UI is
    // generated by `npm run build` and is not committed. Make sure a (possibly empty) directory
    // exists so a fresh clone or a build without the web stage still compiles. The runtime falls
    // back to a built-in page when the folder is empty.
    let out_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/out");
    if !out_dir.exists() {
        std::fs::create_dir_all(&out_dir).expect("failed to create web/out for rust-embed");
    }
}
